#!/bin/bash
printf 'Activating virtual environment\n'
printf '====================================================\n'
source ./venv/bin/activate || exit 1

printf '\nRunning Pip from location: '
pip -V

printf '\nInstalling dependencies\n'
printf '====================================================\n'
pip install -r requirements.txt || exit 1

printf '\nRunning tests with coverage\n'
printf '====================================================\n'
coverage run --branch -m unittest discover || exit 1
coverage report || exit 1
coverage html || exit 1

printf '\nRunning linter for source code\n'
printf  '====================================================\n'
python3 -m pylint leetcode
